name: Sync Fork

on:
  schedule:
    - cron: '* 1 * * *' 
  workflow_dispatch: # on button click

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v2.0.10
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          owner: kimwang1978
          repo: collect-tv-txt
          base: main
          head: main
          
      - name: Log sync status
        run: echo "Fork sync completed successfully."
