name: Sync Fork Git

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily
  workflow_dispatch: # Manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false # Avoid using the default GitHub token
          fetch-depth: 0 # Fetch the full commit history

      # Set Git user
      - name: Set Git User
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions Sync"

      # Add upstream repository
      - name: Add Upstream
        run: |
          git remote add upstream https://github.com/kimwang1978/collect-tv-txt.git
          git fetch upstream

      # Merge upstream branch
      - name: Merge Upstream Branch
        run: |
          git merge upstream/main -m "Sync from upstream"

      # Push changes to the fork
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}

      

